### PR TITLE
feat(endpoints): add endpoints

### PR DESCRIPTION
**Pull request by mostaphaRoudsari**
---

### CODE REVIEW

**Comment by AntoineDao** [comment]
Can we merge this in for now so I can start working on this a bit more over the weekend? I've just spent the evening decoding what a workflow would look like based on the schemas you've written and I'm not gonna lie I'm pretty excited :smile: For posterity's sake here is an example payload I've written up:

```json
{
    "name": "all of the daylight",
    "simulations": [
        {
            "name": "basic daylight factor",
            "type": "DaylightFactor",
            "kind": "GridBased",
            "parameters": {
                "base": "medium",
                "overwrite": "-aa 0.01 -as 4800"
            },
            "model_ids": [
                "uuid-a",
                "uuid-b"
            ],
            "grid_ids": [
                "uuid-1",
                "uuid-2"
            ]

        },
        {
            "name": "CIE point in time",
            "type": "PointInTime",
            "kind": "GridBased",
            "parameters": {
                "base": "medium",
                "overwrite": "-aa 0.01 -as 4800"
            },
            "simulation_type": "illuminance",
            "sky": {
                "north": 0,
                "location": {
                    "latitude": 63.2,
                    "longitude": 23.2,
                    "time_zone": -2,
                    "elevation": 43
                },
                "datetime": {
                    "month": 5,
                    "day": 17,
                    "hour": 12,
                    "minute": 0,
                    "is_leap_year": false
                },
                "sky_type": "+i"
            },
            "model_ids": [
                "uuid-a",
                "uuid-b"
            ],
            "grid_ids": [
                "uuid-1",
                "uuid-2"
            ]
        },
        {
            "name": "ClimateBased point in time",
            "depends_on": "CIE point in time",
            "type": "PointInTime",
            "kind": "GridBased",
            "parameters": {
                "base": "medium",
                "overwrite": "-aa 0.01 -as 4800"
            },
            "simulation_type": "illuminance",
            "sky": {
                "north": 0,
                "location": {
                    "latitude": 63.2,
                    "longitude": 23.2,
                    "time_zone": -2,
                    "elevation": 43
                },
                "datetime": {
                    "month": 5,
                    "day": 17,
                    "hour": 12,
                    "minute": 0,
                    "is_leap_year": false
                },
                "direct_irradiance": 342.2,
                "diffuse_irradiance": 32.4
            },
            "model_ids": [
                "uuid-a",
                "uuid-b"
            ],
            "grid_ids": [
                "uuid-1",
                "uuid-2"
            ]
        }
    ]
}
```

**Comment by mostaphaRoudsari** [comment]
Hi @AntoineDao, Feel free to rebase and merge! And the workflow looks correct to me. I think the real exciting parts comes to play once we have inter-dependent simulations. 🚀

**Comment by AntoineDao** [comment]
Let's live on the edge and do it! I'll have a play over the weekend and see where I get to. Having a quick review of this I still think I'll start off running multiple argo workflows from templates rather than custom generating workflows on the fly here as the API seems pretty intense and is not super well documented.

**Comment by AntoineDao** [comment]
🚀

**Pull request merged**
